#!/bin/python3

import sys
from functools import cmp_to_key

def sort(a, b):
   if len(a) == len(b):
      return int(a) - int(b)
   else:
      return len(a) - len(b)

n = int(input().strip())
unsorted = []
unsorted_i = 0
for unsorted_i in range(n):
   unsorted_t = str(input().strip())
   unsorted.append(unsorted_t)
# your code goes here

print("\n".join(sorted(unsorted, key=cmp_to_key(sort))))